### ISSUE TITLE
Update php-datadogstatsd dependency to newer version

### ISSUE THREAD

**Issue by NoelDeMartin** [chaseconey/laravel-datadog-helper#12]
The current version of the `php-datadogstatsd` library, 0.4.0, was released over two years ago. Since then, a 1.0.0 version has been released among others.

In particular, one notable difference would be the support of UDS that simplifies the usage in dockerized environments and was released in version 1.2.0: https://github.com/DataDog/php-datadogstatsd/releases/tag/1.2.0

**Comment by chaseconey** [comment]
Hey @NoelDeMartin - yeah I noticed the new major version that came out very end of 2017. I definitely did think about pulling that in, but there wasn't much benefit at the time. Now that there are some actual improvements being made to that core library, it may be time to revisit that line of thinking.

The other challenge it is a complete re-work of the API so the package will definitely have to be, more or less, reworked completely (not necessarily a bad thing).

I will look into this when I get some free time for sure.

Thanks

**Comment by NoelDeMartin** [comment]
@chaseconey Ok, Thank you. The good part is that the API overall seems to be the same, so this package's interface can stay the same and it shouldn't be a problem for people to upgrade.
