### ISSUE TITLE
Datadog class could use @method annotations to help code completion

### ISSUE THREAD

**Issue by prodikl** [chaseconey/laravel-datadog-helper#17]
For example:

![image](https://user-images.githubusercontent.com/4628774/83914011-69057e00-a73e-11ea-87a3-a44c2c169b75.png)

When I dig into the class, the head only says:

![image](https://user-images.githubusercontent.com/4628774/83914084-8a666a00-a73e-11ea-9445-606f83af7881.png)

I think adding some method annotations to hint the IDE (and the developer) as to what methods are available and the param should be would be very helpful.

What class does this proxy to?

I'm happy to open a PR

**Comment by chaseconey** [comment]
@prodikl That's a great idea. If this is something you are willing to PR, I will definitely accept the contribution. Otherwise we can leave the suggestion open I can work on it as time permits.

**Comment by prodikl** [comment]
I'm happy to open a PR as it's something I'm using in a project and would like to have it. I haven't dug too far, but which class is this proxying? I'm not super sure which class's methods I should mark this up with. 

Thanks for the quick response

Edit: Ah I see it proxies `datadog/php-datadogstatsd/DogStatsd` - I'll mark it up with that class's public methods

**Comment by prodikl** [comment]
@chaseconey Just opened a PR for your review: #18

**Comment by prodikl** [comment]
@chaseconey Just wanted to check in to see what you think, thanks!

**Comment by prodikl** [comment]
Hey there, have you had any time to review this PR?
Thanks

**Comment by prodikl** [comment]
Hello there,
Any chance you could review this?
Thanks
