### ISSUE TITLE
Call to undefined method ChaseConey\LaravelDatadogHelper\Middleware\LaravelDatadogMiddleware::isDeferred()

### ISSUE THREAD

**Issue by akbarabustang** [chaseconey/laravel-datadog-helper#19]
Got this issue when adding ChaseConey\LaravelDatadogHelper\Middleware\LaravelDatadogMiddleware::class to the laravel 7 config/app provider

**Comment by chaseconey** [comment]
Hello @akbarabustang - can you give a little bit more info for me?

Reading what you have so far, I think you are putting the Middleware line in the app config (in `config/app.php`). As per the instructions, that line should go in your Kernel (in `app/Http/Kernel.php`).

Let me know if that helps or provide some extra details for me if you could.
