### ISSUE TITLE
How does the prefix work?

### ISSUE THREAD

**Issue by morfin** [chaseconey/laravel-datadog-helper#2]
I setup datadog-helper.php prefix config, but calling \Datadog::increment('test'); does not add it automatically. Anything else I need to do?

**Comment by chaseconey** [comment]
Sorry for the slow response - this got lost in the sea of GitHub notifications I guess :(.

Can you show me your config and the sample code where you are using it?

**Comment by chaseconey** [comment]
Added some examples and more docs in the README. Should answer any questions you have.
