### ISSUE TITLE
Durations are currently logged in seconds

### ISSUE THREAD

**Issue by nanaya** [chaseconey/laravel-datadog-helper#20]
I can't be the only one confused about this but I can't find existing issue on this line:

https://github.com/chaseconey/laravel-datadog-helper/blob/60125f22075d2a6fa2900810674b5016294bdc6e/src/Middleware/LaravelDatadogMiddleware.php#L50

It uses `::timing` (milliseconds-based) instead of `::microtiming` (seconds-based) even though the function is being timed using `microtime` (seconds-based) and thus the resulting data are all in seconds.

It's not really big problem although the numbers are all rather small as request times aren't usually expected to even exceed one second (and the unit being passed is wrong).

Additionally, the corresponding functions' time argument are specifically documented as [seconds for `->microtiming`](https://github.com/DataDog/php-datadogstatsd/blob/25f6f73c2becf892241cb8574b6c19bbd9b17e0c/src/DogStatsd.php#L151) and [milliseconds for `->timing`](https://github.com/DataDog/php-datadogstatsd/blob/25f6f73c2becf892241cb8574b6c19bbd9b17e0c/src/DogStatsd.php#L137).

**Comment by chaseconey** [comment]
Thanks @nanaya. Should be taken care of in `1.2.1`.
