### ISSUE TITLE
Would it be useful to have an option to log the route uri vs. full url?

### ISSUE THREAD

**Issue by ChrisEdwards** [chaseconey/laravel-datadog-helper#9]
I modified the code to log the route's uri rather than all distinct urls. I felt this was a better set of metrics than each individual url. If you have restful apis with ids in route params, datadog will treat each instance of a resource as a new metric.

This change would mean I choose to either (1) report by url, which would give me one metric tag per unique url, or (2) report by route, which would give me one metric per route that aggregates all the urls that hit that route.

Example of per-url tags (4 unique url requests = 4 url tags):
1 x url = https://example.com/users/1
1 x url = https://example.com/users/2
1 x url = https://example.com/users/1/preferences
1 x url = https://example.com/users/2/preferences

Example of per-route urls (4 unique url requests = 2 route tags):
2 x route = /users/\_userid\_ 
2 x route = /users/\_userid\_/preferences

I feel these metrics are more meaningful because (1) I can see the aggregate metrics of each route to help manage performance of my code, and (2) lower the total number of metrics in DataDog (which will lower my DataDog costs).

If you are interested in this feature, I would be glad to submit a pull request.

**Comment by ajtrichards** [comment]
This feature would be of interest to me @ChrisEdwards

**Comment by chaseconey** [comment]
@ChrisEdwards my use case is that I am pretty interested in the individual urls, but I can also see wanting to know generic endpoints rather than the specifics. I am trying to think of the best way to handle generically.

I think the best bet would be to add a new optional tag to it below here:
https://github.com/chaseconey/laravel-datadog-helper/blob/master/src/Middleware/LaravelDatadogMiddleware.php#L46

Would you like to try your hand at a PR for that?

**Comment by crabmusket** [comment]
The Datadog documentation says not to use user IDs in tags: https://docs.datadoghq.com/tagging/#defining-tags

> Tags shouldn’t originate from unbounded sources, such as EPOCH timestamps, user IDs, or request IDs. Doing so may infinitely [increase the number of metrics](https://docs.datadoghq.com/developers/metrics/custom_metrics/#how-is-a-custom-metric-defined) for your organization and impact your billing.

I've been using a middleware that tracks request timing like this:

```php
        Datadog::timing(self::prefix($metric), $duration, 1, [
            'status_code' => $response->getStatusCode(),
            'method' => $request->method(),
            'action' => $request->route()->getActionName(),
        ]);
```

The `getActionName` returns something like `\App\Http\Controllers\AppController@getThing` so I can filter on that.

**Comment by chaseconey** [comment]
Hey @crabmusket - my use case is that I have relatively low number of endpoints being hit, but I can totally see the need to look at other axis. Not sure the best way to handle though. We could provide additional Middleware to be used out of the box, or maybe we create a nice way for people to create their own (as you have done above). Any other ideas?

**Comment by crabmusket** [comment]
I guess a config flag to control whether the request URL is tracked? Or maybe just a note in the readme to let people know this is happening and that they might want to change it. Providing a different middleware by default might be nice, too.
